name: Push to Another Repository

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Configure Git
        shell: bash
        env:
          HVLGITUSERNAME: ${{ secrets.HVLGITUSERNAME }}
          HVLGITPASS: ${{ secrets.HVLGITPASS }}
        run: |
          echo '#!/bin/bash' > git-askpass.sh
          echo '$HVLGITUSERNAME:$HVLGITPASS' >> git-askpass.sh
          chmod +x git-askpass.sh
          git config --global user.name "$HVLGITUSERNAME"
          git config --global user.password "$HVLGITPASS"
          git config --global core.askpass $PWD/git-askpass.sh

      - name: Push changes
        shell: bash
        run: |
          git remote add hvlGit https://ider-database.westeurope.cloudapp.azure.com/Bonobo.Git.Server/DAT109-Prosjekt-TexasHoldem.git
          git push hvlGit HEAD:main
